version: "3.8"
services:
  backend: 
    build: ./backend
    container_name: backend_c
    ports: 
      - '5000:5000'
    env_file:
      - /backend/.env

  frontend: 
    build: ./frontend
    container_name: frontend_c
    ports: 
      - '3000:3000'
    stdin_open: true
    tty: true
    